version: '3.8'
services:
  nest-api:
    container_name: nest-api
    build:
      context: ..
      dockerfile: resources/Dockerfile
    ports:
      - '3350:3350'
    depends_on:
      - postgres
      - redis
    env_file:
      - ../.env
    networks:
      - app-network
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ../.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    name: nest-db
  redis-data:
    driver: local